---
version: '3'

set: [pipefail]
shopt: [globstar]

dotenv: ['.env']

vars:
  BOOTSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  TALOS_DIR: '{{.ROOT_DIR}}/talos'
  TALOSCONFIG: '{{.ROOT_DIR}}/talos/clusterconfig/talosconfig'
  TERRAFORM_DIR: '{{.ROOT_DIR}}/terraform'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/talos/kubeconfig'
  SOPS_CONFIG: '{{.ROOT_DIR}}/.sops.yaml'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.TALOSCONFIG}}'

includes:
  talos: .taskfiles/talos
  template: .taskfiles/template
  pve: .taskfiles/pve
  terraform:
    taskfile: .taskfiles/terraform
    dir: '{{.TERRAFORM_DIR}}'

tasks:

  default: task --list
